### PR TITLE
Add support for reading entry attachments

### PR DESCRIPTION
**Pull request by SaltwaterC**
This is fairly straight forward. Basically reused the `ProtectedDecryptor` idea for attachments which are being saved in the `KeePassFile/Meta` XML node rather than the entry itself which means the state needs to be passed down the recursive `Group::from_xml`.

### CODE REVIEW

**Comment by SaltwaterC** [comment]
Actually, there's one more change that's necesary. I only handled compress attachments as this is by default and I haven't found a way to disable compression in either KeePass or KeePassX/C. However, the code needs to take into consideration the `Compressed` attribute of the `KeePassFile/Meta/Binaries/Binary` node.

**Comment by SaltwaterC** [comment]
Can't find the actual KDBX 3.1 spec, however I assume that even the not compressed attachments are also saved as Base64 to play nice with XML. They might be actual binary attachments. I have pushed the change I was writing about in my previous message.

**Comment by mjwhitta** [comment]
I've again merged via the cli. I then added a commit that addressed some of the refactoring I mentioned I wanted to do earlier. Not much of it affected your stuff other than I added begin/rescue blocks around the base64 decoding in case it ever encountered data that wasn't encoded. I hope I didn't break anything you were depending on. All the tests still pass. If somethings broken, let me know or send a merge request fixing it.

**Comment by SaltwaterC** [comment]
The only issue I see with the case insensitive approach for attributes is the interoperability with KeePass ports. KeePassX/KeePassXC seem quite popular and I use them on macOS/Linux.

While KeePass rejects attributes which already exists with a case insensitive match, KeePassX/C do not. KeePass doesn't seem to be bothered by this aspect.

The file names OTOH are fully case sensitive on either implementation. While Windows/macOS use rather case preserving case insensitive filesystems, on Linux/BSD the typical filesystem is case sensitive.

While it doesn't break anything, and there are workarounds for the case insensitive behaviour or `additional_attributes`, `has_attribute?`, and `has_attachment?`, it's certainly not ideal.

Well, code is better than words for showing the WTF moments: https://gist.github.com/SaltwaterC/90aa63b18e8c44049eb1fc8b16f2263b

**Comment by mjwhitta** [comment]
I completely agree. This is one of those situations where I confused my methods or use-cases with other peoples'. I just pushed a couple commits that address this. Primarily, I made `has_blah?` methods case-sensitive and added `has_blah_like?` methods that are case-insensitive. I also tried to mirror this to other places for consistency.

My experience with KeePass is fairly limited so if you have any more ideas or fixes, keep those merge requests coming! =)

**Pull request merged**
